apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: habib0905/rapidcomp:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000   
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: production
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 3000
      targetPort: 8000
      nodePort: 31000   
